"""The bare-name ALIAS MAP for faculty-derived capabilities -- a data module (sweep 124).

seed_from_mind auto-registers every public UnifiedMind method from its docstring but assigns NO
aliases, so bare method names (agent, scene, query, material, ...) get shadowed in find_capability by
a descriptively-titled sibling and become undiscoverable. Every entry below is a stranger-phrasing a
user would actually type, so each method surfaces for its own concept (Discoverability audit D1).

WHY A SEPARATE FILE: this table grows by design -- each discoverability sweep adds phrasings measured
against the catalog exam -- and it pushed holographic_catalog.py over the 2,000-line giant budget. Data
apart from logic. It is a DICT: grep the key before adding one (a later duplicate key silently wins
and the earlier entry becomes dead code -- the duplicate-key audit, which globs holographic_catalog*.py,
catches it by line number). Never fix a dark bare name with a descriptive RENAME: that is the wave
mechanism that created the darkness.
"""

#: ALIAS MAP for faculty-derived capabilities. seed_from_mind auto-registers every public mind method from its
#: docstring but assigns NO aliases, so bare method-names (agent, scene, query, material, ...) get shadowed in
#: find_capability by a descriptively-titled sibling and become UNDISCOVERABLE. These are stranger-phrasings a
#: user would actually type, so each method surfaces for its own concept. (Discoverability audit D1.)
# sweep 129: two dead rows removed ('autoboot' is a lecore-level function, 'holographic_coldstore' a
# module name) -- this table is consulted BY MIND-METHOD NAME at registration, so those keys were
# never read; both phrasings already land on their real cards. The selftest below keeps it so.
_METHOD_ALIASES = {
    # D1 REGRESSION, SECOND WAVE (post-merge). Ranking is GLOBAL: ~57 capabilities arrived with two merges and
    # pushed these 25 bare method-names out of the top-15 for their OWN name, which is the audit's definition
    # of dark. Nothing about them changed -- their neighbours did. Fixed the documented way: stranger
    # phrasings, written from a user's mouth rather than the implementer's.
    # D1 REGRESSION, THIRD WAVE. Same mechanism again: the creature/anatomy merge added capabilities and
    # pushed ten more bare names out of the top-15 for their own name. Nothing about them changed. Written
    # from a user's mouth, as the entries below were.
    # D1, FOURTH WAVE, and I caused this one: registering "Explain a stream (...)" pushed the bare
    # method-name `explain` (why are two RECORDS similar) out of the top-15 for its own name. The
    # descriptive title outranks the generic verb, exactly as the earlier waves did. Aliases written
    # from what a caller comparing two records would actually type.
    # D1, FIFTH WAVE, and this session caused it: the science-instrument + media-drift merges
    # (~15 new descriptively-titled entries full of "generate"/"train"/"drift" language) pushed
    # four more bare names out of the top-15 for their own name. Same mechanism as every wave:
    # ranking is global, the neighbours changed, the methods did not. Aliases from the caller's
    # mouth, per the standing rule.
    # D1, SIXTH WAVE, caused by the compression arc (C-1..C-3): three codec entries dense with
    # "train"/"drift"/"code"/"model" language re-darkened drift_train / drift_generate /
    # train_model despite their wave-5 aliases. Same mechanism; the fix is MORE aliases from
    # the caller's mouth (the wave-5 sets stay -- they route, they just no longer outrank).
    # D1, SEVENTH WAVE, caused by merging the codec-arc aliases WITH the unicron
    # aliases: the union of two dense blocks ("save a checkpoint", "compress",
    # "store") re-darkened the bare names place / save. Same mechanism as waves
    # 5 and 6; same fix -- caller's-mouth aliases so the short names outrank.
    "place": ("move an object in the scene", "rotate an object", "scale an object",
              "position an item at coordinates", "transform an object in the world"),
    "save": ("save my mind to disk", "persist the mind", "write the mind to a file",
             "store this session's memory", "save state"),
    "unicron_forward_runtime": ("run an llm forward pass", "numpy transformer inference",
                        "generate text from a checkpoint", "evaluate perplexity of a model",
                        "own the forward pass", "run a qwen model in lecore",
                        "execute a gdn hybrid model", "fast generation with a state cache",
                        "snapshot the model's state", "rewind a conversation",
                        "branch a conversation into two futures", "fork the model's timeline",
                        "carry state between generation calls"),
    "unicron_resident_memory": ("be inside the model", "install a memory expert in a model",
                                "holographic rag inside an llm", "steer a model with lecore memory",
                                "resident expert in the residual stream",
                                "give the model perfect recall"),
    "unicron_bundle": ("bundle the engine with the model", "self contained model",
                       "ship a model that carries lecore", "model that runs anywhere without install",
                       "package everything into one folder", "make the model include the engine"),
    "unicron_capability_tools": ("advertise the model's features as tools",
                                 "openai tool schemas for every capability",
                                 "what can this model do", "function calling schema for lecore"),
    "unicron_grounded_generate": ("pick the most grounded answer",
                                  "generate several answers and choose the best",
                                  "best of n with a verifier", "reduce hallucination by branching",
                                  "let the model think before answering"),
    "unicron_retarget": ("give the model new abilities",
                         "transform qwen into a galvatron",
                         "improve a model where it actually needs it",
                         "plan what to change in a checkpoint",
                         "which layers should i modify"),
    "unicron_autoscale_memory": ("bigger context window", "make the model handle long documents",
                                 "scale memory to a target length",
                                 "multi timescale memory", "beat the context limit"),
    "unicron_hrnn_grow": ("add a memory channel to the model",
                          "give the model long memory for free",
                          "grow a new head instead of reusing one",
                          "extend memory without hurting quality"),
    "unicron_hrnn_bake": ("give the model a longer memory",
                          "make a head remember for longer",
                          "hrnn inside the weights", "retune the decay gates",
                          "why does the model forget so fast",
                          # from a downstream builder's own vocabulary (lecore-hrr-gpt2 model card):
                          # his gated_scan IS this recurrence -- S_t = a*S_(t-1) + b*k v^T
                          "gated scan", "linear attention", "holographic attention",
                          "associative scan", "decay gate",
                          "chunked scan for recurrence", "gated delta rule"),
    "unicron_load_factors": ("make the model run faster", "speed up inference",
                             "use the factored weights at runtime",
                             "faster forward pass", "why is my smaller model not faster"),
    "unicron_gather_attention": ("make attention actually faster",
                                "skip the keys we already ruled out",
                                "sparse attention that is really sparse",
                                "stop scoring keys we do not use"),
    "unicron_kv_compress": ("much longer context", "shrink the kv cache",
                           "fit more tokens in the same memory",
                           "compress attention cache", "run out of memory on long prompts"),
    "unicron_fold_correction": ("bake the correction into the model",
                               "make a fix part of the weights",
                               "turn a low rank patch into neurons"),
    "unicron_residual_correction": ("undo quantization damage",
                                   "recover accuracy after compressing",
                                   "predict the error and subtract it",
                                   "cheaper than adding another bit"),
    "unicron_requantize": ("shrink the model properly", "quantize by measurement",
                           "pick bit width per tensor", "compress a heavy tailed model",
                           "make the checkpoint smaller for gguf"),
    "unicron_refactor": ("make the model smaller without breaking it",
                         "decompose and rebuild a model", "factor the weights",
                         "shrink a checkpoint with a measured budget",
                         "rebuild a model holographically"),
    "unicron_progbake": ("store a shader inside the model",
                         "put code into the weights", "programs as model data",
                         "hide data in unused vocabulary",
                         "project a program out of a hypervector"),
    "unicron_harden": ("prove the model really has lecore",
                       "test the install under abuse",
                       "does the layer still work after quantizing",
                       "end to end check of an installed model"),
    "unicron_evolve": ("train without gradients", "evolution strategies",
                       "optimize something that has no derivative",
                       "population search over model weights",
                       "train the lecore additions into a model"),
    "unicron_assess": ("measure a model so someone else can judge it",
                       "compare two assimilation runs",
                       "which step actually helped", "export a model report"),
    "unicron_deployable": ("can this model run in ollama",
                           "is the galvatron actually usable",
                           "check it converts to gguf",
                           "is it as good as the original",
                           "will this work outside lecore"),
    "unicron_model_store": ("store the model in our own format",
                            "compatibility wrapper for a model",
                            "keep weights compressed on disk",
                            "produce a normal checkpoint on demand",
                            "smaller model file that still loads"),
    "unicron_tensor_map": ("how are the tensors in this model related",
                          "encode a weight matrix as a hypervector",
                          "which tensors look like each other",
                          "find a tensor that does not fit",
                          "structure of a safetensors file"),
    "unicron_measure": ("is this difference real or noise",
                        "perplexity with error bars",
                        "did that change actually help",
                        "how many tokens do i need to measure this",
                        "compare two models honestly"),
    "unicron_sidecar": ("add lecore without touching the model",
                        "wrapper in front of a model",
                        "keep the base file untouched",
                        "adapter file next to a checkpoint",
                        "turn lecore on and off"),
    "unicron_install_facts": ("teach the model something new in the weights",
                             "make it answer a question it could not",
                             "store a fact the model will recall",
                             "can this model even hold facts",
                             "edit what a model knows"),
    "unicron_vsa_run": ("make the model do vsa algebra itself",
                       "install unbind as neurons",
                       "run holographic memory in the forward pass",
                       "lecore computing inside the weights"),
    "unicron_memory_search": ("search memory from inside the model",
                              "let the model look things up itself",
                              "give the model a searchable index",
                              "retrieve a passage from a partial cue",
                              "expand what the model can remember"),
    "unicron_router": ("let the model decide when to use a capability",
                       "gate a circuit on the prompt",
                       "first layers decide what later layers do",
                       "only search when the prompt asks",
                       "decision inside the forward pass"),
    "unicron_prepend_layers": ("add a lecore layer to any model",
                               "give a model extra layers up front",
                               "bios layer before the model starts",
                               "work with models we know nothing about",
                               "empty layer that changes nothing"),
    "unicron_prefix_cache": ("speed up a long conversation",
                             "stop re-reading the whole chat history",
                             "reuse work from earlier turns",
                             "cache prompt prefixes"),
    "unicron_state_io": ("save what the model has accumulated",
                         "persist lecore memory between sessions",
                         "what does the harness need to store",
                         "restore a conversation's memory",
                         "export the recurrent state"),
    "unicron_reserve_keys": ("make a memory that never gets overwritten",
                             "why did the model forget that",
                             "protect a slot in the recurrent state",
                             "permanent memory across a long conversation"),
    "unicron_install_lecore": ("install lecore into a model",
                               "put the whole engine in the weights",
                               "build a model with lecore inside",
                               "give this model memory and routing"),
    "unicron_install_deepseek_v4": ("install lecore into deepseek v4 flash",
                                    "hrr attach for deepseek v4",
                                    "deepseek v4 sidecar registers and passages",
                                    "flash is not qwen gated deltanet"),
    "unicron_write_policy": ("decide what is worth remembering",
                             "what should go in memory",
                             "pick the important parts of a passage",
                             "which tokens surprised the model"),
    # THE WORKING INVOCATION, because there was no caller anywhere in the tree and
    # the config keys it needs (n_layers, rms_eps) are NOT what a HuggingFace
    # config.json provides -- passing text_config straight in dies three modules
    # deep on KeyError. load_runtime()/load_weights_dir() build the normalized
    # pair; nothing else does.
    "unicron_early_exit": ("skip layers when the answer is already decided",
                           "speed up inference by exiting early",
                           "how do I make the model faster",
                           "stop climbing the layers",
                           "where in the model is the answer already known",
                           "make the model faster without changing it",
                           "shortcut through the layers",
                           "which tokens need the whole model"),
    "unicron_adapt": ("work out what kind of model this is",
                      "read a checkpoint with no config",
                      "install into a model we have never seen",
                      "infer hidden size and layer count from tensors"),
    "unicron_self_write": ("let the model store things on its own",
                           "decide what to remember without being told",
                           "the model writes to its own memory",
                           "automatic storage of surprising input"),
    "unicron_sequence": ("store a sequence so order matters",
                        "remember which came first",
                        "encode position in a hypervector",
                        "hierarchy that a bundle cannot express"),
    "unicron_hlb": ("cheaper binding operator",
                    "bind without storing a matrix",
                    "hadamard binding instead of convolution",
                    "make an installed circuit smaller"),
    "unicron_model_vault": ("save a trained model and run it later",
                            "store a drift model holographically",
                            "recall a model from storage",
                            "keep a trained thing without keeping its encoder"),
    "unicron_program_library": ("find the right vsa program for a situation",
                                "run a stored holographic program",
                                "programs that discover themselves",
                                "composable vsa procedures"),
    "unicron_device": ("use the gpu if there is one",
                       "run the model on a graphics card",
                       "check cpu or gpu is being used",
                       "make sure it still works without a gpu"),
    "unicron_vm_unit_install": ("put the virtual gpu inside the model",
                          "which cache tiers can live in weights",
                          "install a gather unit into a layer",
                          "can the memory hierarchy be baked in"),
    "unicron_install_plan": ("how should i install this operator",
                             "can a whole pipeline fit in one layer",
                             "install an iterative solver into weights",
                             "fuse a chain of transforms"),
    "unicron_install_order": ("what order should i install things in",
                              "do these two steps interfere",
                              "which step has to go last",
                              "did this step change what it said it would"),
    "unicron_long_context": ("context of a billion tokens",
                             "remember across an unbounded stream",
                             "how often must memory be refreshed",
                             "what limits how far back the model can see",
                             # WHY these were added: a session-long argument about billion-token context never
                             # surfaced this capability because none of the phrasings the ARGUER used were here.
                             # Aliases come from the user's mouth, including the frustrated user's.
                             "billion scale",
                             "billion token context",
                             "handle a huge context window",
                             "unbounded stream memory",
                             "constant size memory of a long stream",
                             "scale beyond what fits in memory",
                             # the float32 register cliff (1.0 at 30k writes, 0.057 at 140k) is THE
                             # fact a million-token linear-attention claim must survive:
                             "precision limit of a recurrent state",
                             "float32 state degrades",
                             "million token context",
                             "how long can the state survive"),
    "unicron_self_heal": ("repair memory without a backup copy",
                          "fix a register that has drifted",
                          "is the stored value still trustworthy",
                          "clean up a corrupted memory slot",
                          "refresh a drifting state",
                          "state refresh schedule",
                          "keep a recurrent state healthy over a long run"),
    "unicron_actr": ("rank memories by recency and frequency",
                     "which memory should i retrieve",
                     "forget what stopped being useful",
                     "activation ranking for stored items"),
    "unicron_nullspace": ("install without disturbing what the model knows",
                          "make an edit that preserves existing behaviour",
                          "project a weight change onto unused directions",
                          "reduce the cost of installing a circuit"),
    "unicron_state_track": ("keep count across a long sequence",
                            "track a state machine while reading",
                            "something attention cannot compute",
                            "remember a running total"),
    "unicron_hybrid": ("combine the language model with exact memory",
                       "decide when to generate and when to recall",
                       "which tokens should memory handle",
                       "use both the model and the store together"),
    "unicron_runtime": ("run a model using its installed leCore parts",
                        "the loop that uses memory and the model together",
                        "serve a model with exact recall",
                        "actually use what was installed"),
    "unicron_ref": ("get a handle for an object over http",
                    "return something json cannot carry",
                    "pass a live object between invoke calls",
                    "why did this capability return a memory address"),
    "unicron_turn_memory": ("keep every turn instead of forgetting old ones",
                            "a separate memory per conversation turn",
                            "stop the register file filling up",
                            "hold more facts than slots"),
    "unicron_recipe": ("ship the install without shipping the model",
                       "why is the installed model so much bigger",
                       "store the rule instead of the bytes",
                       "send someone a leCore install"),
    "unicron_vm_install": ("put a vsa program into the model weights",
                           "install an opcode sequence",
                           "make the model run a holographic program",
                           "fuse several operations into one"),
    "unicron_branch": ("make the model choose between two operations",
                       "an if statement in the weights",
                       "multi step reasoning inside the model",
                       "what kind of thinking can be installed"),
    "semantic_to_scene": ("turn a described scene into a renderable one",
                          "render what scene_from_image produced",
                          "convert a semantic scene to sdf geometry",
                          "make a described scene renderable"),
    "composite_layers": ("blend a stack of layers into one image",
                         "apply a blend mode like multiply or screen",
                         "flatten a layered document",
                         "the same compositing every app should use"),
    "live_session": ("let two apps edit one document at once",
                     "track revisions and who is present",
                     "a change feed for collaborative editing",
                     "coordinate concurrent editors"),
    "container_kinds": ("what section kinds does this build understand",
                        "publish an image any app can read",
                        "why is this section not editable here",
                        "the canonical image section kind"),
    "fem_simulate": ("simulate a soft body with muscles",
                     "finite element physics on a tet mesh",
                     "make flesh deform under activation",
                     "neo-hookean elasticity"),
    "fem_rest_quality": ("check a tet mesh before simulating it",
                         "are my tetrahedra degenerate",
                         "element quality report",
                         "why is my simulation stiff"),
    "wrap_to_field": ("wrap a template mesh onto a shape",
                      "fit a base mesh to a scanned field",
                      "shrinkwrap without breaking the mesh",
                      "did the wrap stay usable"),
    "pose_is_safe": ("will this skinning pose pinch",
                     "check a rig for candy wrapper collapse",
                     "how far can this joint twist",
                     "linear blend skinning volume loss"),
    "shape_from_shading_prior": ("fix the convex concave flip in a depth map",
                                 "remove bas relief ambiguity",
                                 "combine shape from shading with a prior",
                                 "my depth map is inside out"),
    "groom_region_map": ("paint a per vertex weight from regions",
                         "build a groom mask",
                         "a falloff attribute over a mesh",
                         "blur a weight map across the surface"),
    "make_corrective": ("add a corrective blendshape",
                        "one local blendshape target",
                        "fix a deformation at a joint",
                        "is my blendshape actually local"),
    "levers": ("what do I do when I hit a wall",
               "ways to beat a capacity limit",
               "the six levers",
               "I am blocked what are my options",
               "how do I get past a memory limit",
               "is this limit structural"),
    "ouroboros": ("read and write a running model's memory",
                  "the closed memory loop",
                  "edit a state matrix with no forward pass",
                  "write a fact into a model and delete it again"),
    "lean_export": ("prove something and export it to lean 4",
                    "get a machine checkable proof",
                    "have an external kernel verify this",
                    "formal certificate for a derivation"),
    "optional_backends": ("what optional things can I install",
                          "do I need lean or a gpu",
                          "how do I turn on gpu acceleration",
                          "is anything missing from my install",
                          "what would make this faster"),
    "read_image_section": ("read an image another app published",
                           "get the picture out of a container",
                           "consume a lecore.image section"),
    "boot_substrate_keys": ("which tensors hold the boot record",
                            "what must not be quantized to bf16",
                            "protect the model identity when exporting"),
    # A BARE-NAME FACULTY IS SHADOWED BY ITS DESCRIPTIVELY-TITLED SIBLINGS:
    # searching "grow_at" returned the morphogenesis and crystal entries and
    # never grow_at itself, so the auto-registered capability was DARK. Aliases
    # written from a user's mouth, not the implementer's.
    "grow_at": ("what does the growth look like partway through",
                "sample a growth at a point in time",
                "the state of a grower at progress t",
                "scrub a growth animation"),
    # THE FRONT DOOR WAS DARK. `lecore.autoboot()` is the documented way to start
    # -- it is in the README -- and find_capability("boot up lecore") returned
    # holographic_boot (a MODEL boot record, unrelated) with autoboot nowhere.
    # It is a MODULE function, not a mind method, so nothing auto-registered it:
    # the catalog only sees the mind's surface, and the one call a newcomer makes
    # first lives outside that surface.
    # EXTERNAL MEMORY: the phrase a user says, pointed at the pair that does it.
    # learning_load/learning_save ARE the external memory -- a .lecore container
    # partition on disk that survives the process -- and neither surfaced for
    # "external memory", "memory that persists between runs" or "load and save
    # what I have learned". The mechanism was fine and the WORDS were missing.
    "learning_load": ("external memory",
                      "load what I have learned",
                      "memory that persists between runs",
                      "restore a saved mind",
                      "read a lecore partition"),
    "learning_save": ("save what I have learned",
                      "write my memory to disk",
                      "persist the mind between runs",
                      "make a lecore partition"),
    "teach": ("teach it a fact",
              "tell lecore something to remember",
              "add knowledge by hand",
              "pin an established answer"),
    # BARE GENERIC NAMES ARE SHADOWED BY DESCRIPTIVELY-TITLED SIBLINGS, and the
    # buried audit catches them the moment ranking shifts -- which is what
    # happened when auto-registered examples grew from "mind.x(...)" to the real
    # signature. The capability did not change; the search text around it did.
    # THE FIX THE TEST ASKS FOR IS ALIASES, not a shorter example: a one-word
    # name has nothing for a stranger's phrasing to match on.
    "answer": ("just answer my question",
               "route a question to the right place",
               "who should handle this question"),
    "api_use": ("call an endpoint I taught it",
                "use a learned api",
                "invoke a remembered service",
                # sweep 103 merge: the duplicate-key audit caught a second api_use entry
                # SHADOWING this one (dict literal: later key wins) -- phrasings merged
                # here, duplicate deleted. An alias map is a dict; grep before adding.
                "call a learned api endpoint", "source data from an api",
                "query an external service", "call the forecasting service",
                "robotics service call"),
    "capabilities": ("what can this mind do",
                     "list everything available",
                     "introspect the capability registry"),
    "do": ("just do this task",
           "one call to get a job done",
           "orchestrate this for me"),
    "learn": ("teach it one labelled example",
              "show it a training pair",
              "the base learning verb"),
    "restore": ("clean up a degraded measurement",
                "denoise and deblur together",
                "plug and play restoration"),
    "shape_of": ("what does this return",
                 "how do I actually call this",
                 "show me the return shape"),
    # REPAIR FOR A PARTITION THAT GREW. The doctrine-duplication fix stops new
    # growth; it cannot reclaim rows already written, and there was no faculty
    # that could. Aliases from the mouth of someone staring at a bloated file.
    "learning_compact": ("clean up my memory file",
                         "remove duplicate memories",
                         "compact the partition",
                         "my lecore file keeps growing",
                         "dedupe the taught store"),
    # PRUNE's diagnostic for sequential editing. An install writes the same
    # tensors eight times over; perplexity and drift both miss a matrix that is
    # holding its accuracy while becoming numerically fragile.
    "unicron_edit_health": ("is my install degrading the model",
                            "condition number of an edited matrix",
                            "did sequential edits make the weights fragile",
                            "check weight health after installing",
                            "prune condition number check"),
    # Tombstone reclamation. UPDATE is tombstone-and-reinsert, so a table that is
    # written to only ever grows -- 400 rows became 1,260 after five updates.
    # Aliases from the mouth of someone watching a table bloat.
    # DO NOT ASK A MODEL TO MULTIPLY -- it emits the likeliest next token, which
    # is not arithmetic. check_math computes the claims instead.
    "explain_pair": ("why are these two similar",
                     "compare two records role by role",
                     "what do these two have in common"),
    "manifold_chart": ("flatten curved data to a chart",
                       "my embedding is curved not flat",
                       "isomap",
                       "laplacian eigenmaps"),
    "check_math": ("check the math in an answer",
                   "did the model do the arithmetic right",
                   "verify a calculation",
                   "the numbers look wrong"),
    "do_math": ("actually calculate this",
                "evaluate an arithmetic expression",
                "compute it instead of guessing"),
    "table_vacuum": ("my table keeps growing",
               "remove deleted rows permanently",
               "reclaim tombstones",
               "vacuum a table",
               "compact a table after updates"),
    "db_vacuum_idle": ("clean up dead rows automatically",
                       "vacuum every bloated table",
                       "my database is full of dead rows",
                       "sweep tombstones across a database"),
    # THE STALE-REFERENCE PROBLEM. A fact about code stays at T0 while the code
    # moves; nothing connected a memory to the file it describes.
    "teach_about": ("remember this about a file",
                    "teach a fact tied to source code",
                    "record what this module does"),
    "stale_facts": ("which of my notes are out of date",
                    "what did I write about code that has changed",
                    "find stale references in memory",
                    "is my memory still current with the codebase"),
    "unicron_bios": ("what kind of model is this",
                     "probe a checkpoint before touching it",
                     "will this fit in my model", "enumerate a model's layout",
                     "is lecore already installed here"),
    "unicron_install": ("install lecore into a model",
                        "check that the install actually worked",
                        "audit a model for lecore", "set up the layer in a checkpoint",
                        "did the install take"),
    "unicron_query_path": ("let the model look things up itself",
                          "turn the stream into a lookup key",
                          "retrieve a stored fact from a prompt",
                          "the model asks its own memory"),
    "unicron_seeded_channel": ("read hidden data with only a seed",
                              "self describing storage in weights",
                              "payload that needs no original file"),
    "unicron_quantsafe": ("storage that survives gguf",
                         "hide data that quantization cannot erase",
                         "keep a payload through q4 conversion",
                         "write bits into the rounding"),
    "unicron_store_program": ("put code inside the model",
                             "run lecore programs from the weights",
                             "store a program in a checkpoint",
                             "execute instructions stored in weights"),
    "unicron_fountain": ("recover data from any subset of pieces",
                         "erasure codes", "survive losing part of the data",
                         "rateless codes", "luby transform droplets"),
    "unicron_store_route": ("store a generator instead of the data",
                            "decide how to store this payload",
                            "is this data compressible at all",
                            "keep learning after the model ships",
                            "store a rule not the output"),
    "unicron_resilient_store": ("storage that survives damage",
                                "payload that tolerates a dead channel",
                                "keep data even if part of the model is rewritten"),
    "unicron_substrate": ("hide data inside the weights",
                          "use the model as a disk", "storage capacity of a checkpoint",
                          "write files into a model", "how much can i hide in the weights"),
    "unicron_boot": ("boot lecore inside the model", "an operating system in the weights",
                     "regenerate the whole layer from a seed",
                     "store a boot record in a checkpoint",
                     "make the model carry lecore itself"),
    "unicron_call_tokens": ("let the model call capabilities itself",
                            "tool calling baked into the weights",
                            "the model decides to run a function",
                            "capability tokens in unused vocabulary",
                            "model asks for a tool without being told"),
    "unicron_swarm_bake": ("swarm inside the model",
                          "experts that route by content",
                          "run specialists in one forward pass",
                          "mixture of experts in the weights",
                          "inject capability without a prompt"),
    "unicron_vsa_roles": ("structured memory inside the model",
                          "bind subject and object into one vector",
                          "role filler slots for a model", "store relations in a vector",
                          "give the model somewhere to put structure"),
    "unicron_vsabake": ("run vsa inside the model", "hypervector algebra in the weights",
                        "holographic computing space inside a model",
                        "bake bind and unbind into a checkpoint",
                        "make the model do vsa by itself"),
    "unicron_distill": ("train the abilities into the model",
                        "make residents permanent", "teach the weights what the residents do",
                        "absorb runtime behaviour into weights",
                        "distill a galvatron into a plain checkpoint"),
    "unicron_bake": ("bake abilities into the weights",
                     "make the ban survive gguf conversion",
                     "put a memory into the weights themselves",
                     "edit weights instead of hooking the runtime",
                     "keep capabilities after export"),
    "unicron_port": ("run it in ollama", "use the model with llama.cpp",
                     "export for gguf", "make it work in a normal runtime",
                     "what survives outside lecore"),
    "unicron_cache": ("stop redoing the same work", "cache the model's internal work",
                      "speed up repeated lookups", "memoize routing and retrieval",
                      "make the model faster without changing answers"),
    "unicron_toolbelt": ("give the model all the capabilities",
                         "let the model call any tool", "model can run physics and math",
                         "all of lecore inside the model", "capability router for the model"),
    "unicron_memory": ("obsidian alternative", "notes with backlinks",
                       "a second brain for the model", "knowledge graph of my notes",
                       "store notes and query them", "memory the model can write to"),
    "unicron_vault": ("import an obsidian vault", "read a folder of markdown notes",
                      "convert markdown notes into memory"),
    "unicron_knowledge": ("start a conversation with a clean slate",
                          "stop this chat from seeing old conversations",
                          "delete old conversations and notes",
                          "prune what the model remembers",
                          "private session that references nothing",
                          "remember everything i tell the model",
                          "search what the model has been told",
                          "store documents the model can cite later",
                          "make conversation history searchable",
                          "catalog of what the model knows",
                          "reference information from an old conversation"),
    "unicron_scribe": ("let the swarm write its own notes",
                       "internal experts keep reference documents",
                       "agent notes that are searchable later",
                       "partitioned notes from the model's own reasoning"),
    "unicron_sessions": ("keep a conversation going for days",
                         "save and restore the model's context",
                         "multiple conversations at once",
                         "swap contexts in and out", "persistent context store",
                         "manage many chats with one model",
                         "continue where we left off after restarting"),
    "unicron_imbue_package": ("imbue a model", "imbue a checkpoint",
                      "imbued galvatron", "make an imbued model",
                      "give a checkpoint its residents",
                      "make an imbued model", "build an imbued galvatron",
                      "turn weights into a galvatron"),
    "unicron_maximal_specs": ("give the model every capability we have",
                              "maximal galvatron", "wire all the experts at once",
                              "full resident stack for a model",
                              "put as much of lecore in the model as possible"),
    "unicron_best_portable": ("best plain checkpoint we can make",
                              "optimize a model for normal harnesses",
                              "export the strongest compatible model",
                              "measured retention export"),
    "unicron_save_pack": ("package a model with its scaffolding", "ship a galvatron",
                          "save a model plus its residents", "bundle model and experts",
                          "export a model that needs lecore"),
    "unicron_load_pack": ("load a packaged model", "restore a model and its residents",
                          "open a galvatron package", "run a packaged model without lecore"),
    "unicron_serve_openai": ("serve my model with an openai compatible api",
                             "make my model look like a normal api",
                             "chat completions endpoint for my model",
                             "point lm studio at my model", "wrap the model as a standard server"),
    "unicron_hf_wrapper": ("make it work like a transformers model",
                           "drop in replacement for a huggingface model",
                           "generate like a normal model object"),
    "unicron_lazy_weights": ("keep the model compressed in memory",
                             "decompress weights on demand", "run a model with less ram",
                             "compression inside the model", "lazy weight loading",
                             "stream weights as the model needs them"),
    "unicron_export_portable": ("export a model that runs in ollama",
                                "make it work in llama.cpp", "convert to a normal checkpoint",
                                "run our model on huggingface", "portable model export",
                                "ship the model to a standard harness"),
    "unicron_middleout": ("middle out compression", "progressive weight code",
                          "compress a model so i can decode it at any size",
                          "one file many fidelity levels", "truncatable model artifact",
                          "coarse to fine weight encoding", "scalable model storage"),
    "unicron_middleout_decode": ("decode a progressive weight stream at a budget",
                                 "load a model at lower fidelity", "truncate a weight stream",
                                 "read fewer refinement layers"),
    "unicron_capability_resident": ("let the model call a simulation",
                                    "give a model access to physics",
                                    "tool use inside the forward pass",
                                    "model calls lecore capabilities",
                                    "inject a computed answer into the model",
                                    "can the model run a fluid sim",
                                    "give an llm exact math and simulation"),
    "unicron_salience_trigger": ("let the model decide when to search",
                                 "detect when the model is uncertain",
                                 "trigger retrieval on hesitation",
                                 "model asks for help by itself",
                                 "fire a tool only when the model needs it",
                                 "uncertainty detection from hidden states"),
    "unicron_corpus_resident": ("rag inside the model", "give the model a document corpus",
                                "retrieve passages during generation",
                                "search my documents from inside the forward pass",
                                "unlimited knowledge without context window",
                                "ground the model in my own documents"),
    "unicron_hrnn_resident": ("run hrnn on the model's hidden states",
                              "analyze the model's trajectory",
                              "sequence analysis of what the model is doing",
                              "let lecore watch the model think"),
    "unicron_manifold_voids": ("where has the model never been",
                               "find holes in the activation space",
                               "regions the model never visits",
                               "gaps in what a model represents",
                               "void exploration of a model"),
    "unicron_void_probe": ("decode an unvisited state", "what would the model say there",
                           "explore a novel activation", "read out a void"),
    "unicron_carrier": ("write structured data into the model's activations",
                        "side channel inside the residual stream",
                        "exact symbolic state alongside the model's thinking",
                        "use the unused dimensions of the hidden state",
                        "carry key value pairs through the layers",
                        "read back what i wrote into the stream"),
    "unicron_forward_embeds": ("run the model from hidden states",
                               "feed embeddings instead of tokens",
                               "superpose inputs into the model",
                               "run a model on a vector not a token"),
    "unicron_layer_schedule": ("run layers twice", "depth upscaling without retraining",
                               "frankenmerge a model", "make the model deeper with the same weights",
                               "layer recursion", "prune layers at inference"),
    "unicron_screen_routing": ("skip attention work with a summary index",
                               "route attention through block summaries",
                               "cheaper long context without changing the answer",
                               "read the boundary instead of the whole context",
                               "sparse attention that finds the right keys"),
    "unicron_capacity_report": ("how many tokens can the state hold",
                                "o1 state capacity accounting",
                                "how much context does this model really use",
                                "boundary versus volume in a model",
                                "is the state or the kv cache doing the work",
                                "information capacity of a model's state",
                                "holographic capacity audit"),
    "unicron_memory_horizon": ("how far back does the model remember",
                               "real memory length of a recurrent model",
                               "when does the model forget a token",
                               "causal memory horizon"),
    "unicron_attention_waste": ("how much attention compute is wasted",
                                "how many keys actually matter",
                                "sparse attention radius", "is the model doing useless work",
                                "measure redundancy in attention"),
    "unicron_leap": ("generate tokens faster", "speed up my model's output",
                     "speculative decoding with a learned drafter",
                     "make the llm faster without changing what it says",
                     "cache the routes the model takes", "faster inference same output"),
    "unicron_verified_generate": ("fact check the output before it is emitted",
                                  "stop the model from making things up",
                                  "verify claims against sources during generation",
                                  "grounded generation with a checker",
                                  "internal critique and revise loop",
                                  "agent loop without token round trips"),
    "unicron_evidence": ("build an evidence store", "allowed claims for the model",
                         "source spans the model may assert"),
    "unicron_swarm": ("inner monologue for the model", "swarm of agents inside the model",
                      "compiled swarm members", "optimized internal swarm", "certify swarm hooks",
                      "subconscious deliberation", "many agents thinking between tokens",
                      "nested agent swarm", "internal committee for a model"),
    "unicron_swarm_mind": ("generate with an inner monologue",
                           "run the model with a subconscious",
                           "let inner agents vote on the next token",
                           "orchestrate a swarm and merge the result"),
    "look_at": ("camera view matrix", "point the camera at a target", "opengl look at matrix",
                "make a view matrix from eye and target"),
    "unicron_galvatron": ("rebuild a model with resident experts", "put lecore inside the model",
                          "model with a memory expert and a guard", "make a galvatron",
                          "run a model with residents in its forward pass",
                          "hard ban tokens during generation", "repair the model's thoughts",
                          # the Ouroboros organ (this session): the memory manager resident
                          "galvatron with ouroboros", "memory manager in the forward pass",
                          "make him mighty", "galvatron holographic magic"),
    "unicron_council": ("deliberate over alternate continuations", "branch futures and pick the best",
                        "self consistency without a second model", "model council",
                        "compare steered and unsteered generations"),
    "unicron_generator_audit": ("can this data be regenerated from a seed",
                                "does a generator exist for this tensor",
                                "is this compressible to a formula",
                                "check if weights have hidden structure"),
    "unicron_archive": ("archive a fleet of models", "store only the difference from a reference",
                        "deduplicate shared tensors across checkpoints", "store a model as delta",
                        "seed instead of data", "recipe instead of data", "model version control"),
    "unicron_restore": ("restore a model from the archive", "rebuild a checkpoint from deltas",
                        "regenerate a tensor from its seed"),
    "unicron_shelve": ("remember this model", "add a model to the library",
                       "register a checkpoint in memory"),
    "unicron_identify": ("which stored model is this", "identify a mystery checkpoint",
                         "what lineage is this model from", "recognize a model by content"),
    "unicron_report": ("tell me everything about this model", "what should i do with this checkpoint",
                       "full analysis of a model file", "can this model be compressed",
                       "audit a checkpoint", "what are my options for this llm",
                       "one call model diagnosis"),
    "unicron_lineage": ("which model is this based on", "find the base model of a fine tune",
                        "detect model lineage from weights", "who is this checkpoint's parent",
                        "pair a fine tune with its base without metadata"),
    "unicron_delta_store": ("store only what the fine tune changed",
                            "delta storage for models", "ship many fine tunes of one base",
                            "compress the difference between two checkpoints",
                            "lora style storage after the fact", "save a model as a diff"),
    "unicron_delta_apply": ("rebuild a fine tune from a diff", "apply a stored model delta",
                            "interpolate between base and fine tune"),
    "unicron_taskvector": ("extract a capability from a fine tune", "task vector arithmetic",
                           "difference between two checkpoints as a skill", "what did fine tuning add",
                           "pull the learning out of a fine tune"),
    "unicron_imbue": ("add a skill to a model", "inject an expert into a model",
                      "transplant a capability", "graft knowledge into weights",
                      "combine two fine tunes", "give a model new powers",
                      "merge a fine tune into another model"),
    "unicron_heads": ("how many attention heads does this matrix have", "find the head structure",
                      "discover heads in a projection", "dissect a weight matrix into heads",
                      "recover the head count blind"),
    "unicron_depthshare": ("shared structure across many matrices", "do the layers repeat themselves",
                           "how redundant is model depth", "cross layer shared subspace",
                           "is the model one matrix wearing costumes", "depth redundancy of a model"),
    # SWEEP-7 routing fixes (post-merge battery misses, phrasings verbatim):
    "unicron_analyze": ("analyze a trained neural network model", "inspect an llm",
                        "weight matrix analysis", "how well trained is this model",
                        "spectral analysis of weights", "marchenko pastur on my model",
                        "what is inside this llm file", "look inside a checkpoint"),
    "unicron_transform": ("transform a model into a smaller one", "compress a whole checkpoint",
                          "shrink a neural network", "upgrade a trained model", "rewrite model weights",
                          "low rank factorize every layer", "model surgery", "make a model smaller",
                          "make my model smaller without breaking it", "safely compress a model"),
    # UNICRON (part 16): aliases from the caller's mouth -- someone holding a
    # checkpoint file, not someone who knows the module name.
    "unicron_load": ("read model weights", "load a safetensors file", "open an llm checkpoint",
                     "load trained model weights", "parse a model file", "safetensors",
                     "load a gguf file", "llama.cpp model", "dequantize model weights"),
    "unicron_fingerprint": ("hypervector for a whole model", "model fingerprint",
                            "embed a model as a vector", "model signature",
                            "represent a checkpoint holographically"),
    "unicron_subspace": ("principal angles between subspaces", "subspace overlap of two matrices",
                         "compare singular vector spaces", "do two layers point the same way",
                         "grassmann distance between weight matrices"),
    "unicron_assimilate": ("assimilate a model end to end", "one call model pipeline",
                           "defrag a model", "clean and re-export a checkpoint",
                           "optimize a whole llm checkpoint", "reorganize model weights",
                           "process a qwen or llama checkpoint", "full model upgrade pass"),
    "unicron_reconstruct": ("expand a factored model back to dense", "undo model compression",
                            "multiply the u v factors back", "rebuild dense weights"),
    "unicron_retention": ("did the transform keep accuracy", "measure accuracy before and after",
                          "functional retention of a model", "prove the compression is safe",
                          "capability check after surgery"),
    "unicron_localize": ("where is the learned information in the weights", "singular vector localization",
                         "porter thomas test on weights", "which coordinates does this layer use",
                         "localized singular vectors"),
    "unicron_filter": ("denoise model weights", "filter noise out of a weight matrix",
                       "strip the random part of a trained layer", "rmt weight filtering",
                       "compress a checkpoint by keeping outliers", "clean up trained weights"),
    "unicron_trajectory": ("track a model across training checkpoints", "training trajectory of a model",
                           "how did my model change during training", "checkpoint time series",
                           "watch training move the weights", "spectral dynamics of a run"),
    "unicron_compare": ("compare two trained models", "teacher vs student weights",
                        "did distillation work", "diff two checkpoints",
                        "compare model checkpoints"),
    "generate": ("continue this text", "next tokens from the model", "text continuation",
                 "sample from the sequence model", "autocomplete from schema"),
    "train_model": ("train a classifier on sequences", "fit a trajectory classifier",
                    "label sequences and learn", "one call training front door"),
    "drift_train": ("train a generative model on points", "learn a distribution from samples",
                    "fit a drift model", "moments from my data", "point cloud generative model"),
    "drift_generate": ("sample new points from a drift model", "generate from the moments",
                       "draw samples like my data", "run the drift sampler"),
    "explain": ("why are these two records similar", "compare two records field by field",
                "explain a match", "why did these match", "per-role decode of two records"),
    "build_creature": ("make a creature", "generate a creature", "build a whole creature",
                       "create an animal", "one call creature"),
    "build_part": ("make a body part", "build a horn", "generate a foot", "make an eye",
                   "create a claw"),
    "creature_parts": ("body part library", "what parts can i use", "part palette",
                       "list of body parts", "available parts"),
    "make_mixture": ("mix two materials", "smoke and dye", "multi channel matter",
                     "blend substances", "milk in water"),
    "make_surrogate": ("cheap stand-in for a slow function", "approximate an expensive call",
                       "learned shortcut", "cache a function as a model"),
    "rig": ("creature skeleton", "one rig type", "bones and joints", "skeleton for any body",
            "humanoid and creature rig", "articulation"),
    "skin_mesh": ("deform a mesh with bones", "linear blend skinning", "attach a mesh to a skeleton",
                  "bind mesh to bones", "move the mesh with the rig"),
    "terrain": ("make a landscape", "generate ground", "heightfield", "hills and valleys",
                "procedural terrain"),
    "tissue_at": ("what tissue is here", "bone or muscle at this point", "what is inside the body",
                  "sample the anatomy", "is this point bone"),
    "what_is_at": ("what part is on this socket", "which part did i attach", "read back an attachment",
                   "query a socket"),
    "bake_texture": ("bake a texture", "bake lighting to a texture", "bake to uv", "texture baking"),
    "forecast": ("predict the next value", "forecast a series", "time series prediction", "what comes next"),
    "forward_forward": ("forward-forward learning", "train without backprop", "local learning rule"),
    "from_file": ("load from a file", "read a saved mind", "restore from disk"),
    "from_state": ("restore from a state dict", "rebuild from saved state", "resume a mind"),
    "gather": ("gather values by index", "collect entries", "index into a table"),
    "invite": ("invite a collaborator", "share access", "add a participant"),
    "invoke": ("call a faculty by name", "dispatch a method by name", "call a tool by name"),
    "is_manifold": ("is the mesh manifold", "check mesh manifoldness", "watertight check"),
    "load": ("load a saved mind", "open a saved session", "read a mind from disk"),
    "make_water": ("make water", "create a water surface", "water material"),
    "materials": ("list the materials", "what materials are available", "material library"),
    "mesh_repair": ("repair a broken mesh", "fix mesh errors", "clean up a mesh"),
    "mesh_report": ("mesh statistics", "report on a mesh", "mesh health check"),
    "mesh_to_field": ("turn a mesh into a field", "mesh as a field", "sample a mesh as a function"),
    "mesh_to_sdf": ("mesh to sdf", "convert a mesh to a distance field", "signed distance from a mesh"),
    "node_graph": ("build a node graph", "node based pipeline", "wire nodes together"),
    "reproject": ("reproject to a new view", "warp between viewpoints", "reprojection"),
    "scan": ("scan an object", "capture a scan", "photogrammetry scan"),
    "scene_from_image": ("build a scene from a photo", "image to scene", "reconstruct a scene from a picture"),
    "sculpt": ("sculpt a mesh", "push and pull geometry", "digital sculpting"),
    "semantic_scene": ("describe the scene semantically", "scene meaning", "what is in this scene"),
    "shape": ("make a shape by name", "build a primitive shape", "named shape"),
    "use_gpu": ("turn the gpu on", "enable gpu acceleration", "switch to the device"),
    "weld_mesh": ("weld duplicate vertices", "merge coincident vertices", "stitch a mesh"),
    # C2/D1: these constructors ALWAYS existed and worked -- m.render_mesh(m.mesh_box(), m.camera(...)) renders
    # today with no class imports. A downstream audit still reported them "absent", because it searched for
    # make_box / box_mesh / cube / primitive / make_camera and find_capability answered "Catmull-Clark
    # subdivision". A capability find_capability cannot surface does not exist, so the bug was the vocabulary,
    # not the code. Aliases written from the CLIENT's mouth, verbatim where they used them.
    "mesh_box": ("make a box", "box mesh", "cube", "make_box", "box_mesh", "primitive", "create a box",
                 "build a cube", "box primitive", "make a cube mesh", "new box"),
    "mesh_grid": ("make a grid", "plane mesh", "make_plane", "ground plane", "quad grid", "make a plane"),
    "camera": ("make a camera", "make_camera", "create a camera", "new camera", "viewpoint", "eye and target",
               "set up a camera", "camera from eye and target", "pinhole camera"),
    "camera_controller": ("orbit camera", "viewport camera", "pan dolly zoom", "turntable", "orbit the view"),
    "render_mesh": ("mesh to image", "render a mesh", "rasterize a mesh", "picture of a mesh", "mesh render",
                    "draw a mesh", "3d to image"),
    "agent": ('reinforcement learning agent', 'creature that learns from reward', 'action library agent', 'npc brain', 'agent with reward and pain', 'learning game character'),
    "bake": ('bake a slow function into a cache', 'precompute and look up', 'consolidation cache', 'cache an expensive evaluator', 'bake once sample many'),
    "blend": ('blend learned classes', 'mix two concepts', 'interpolate between categories', 'combine learned prototypes', 'projection to create new things'),
    "build_index": ('build a nearest neighbour index', 'index vectors for search', 'make a search index', 'knn index over vectors', 'build an ann index'),
    "build_scene": ('describe a scene in words and build it', 'text to scene', 'make a scene from a description', 'natural language scene builder', 'scene from prompt'),
    "bus": ('shared message bus', 'event bus for the mind', 'publish subscribe channel', 'inter-agent messaging', 'one shared bus'),
    "database": ('a database you own', 'user namespaces over records', 'owned query database', 'personal database', 'namespaced data store'),
    "denoise": ('clean a noisy signal', 'remove noise from a vector', 'denoise by projecting onto a manifold', 'plug and play denoiser', 'restore a corrupted signal'),
    "encyclopedia_is_a": ('parent in the taxonomy', 'one hop up the is-a tree', 'get the category of a concept', 'taxonomic parent', 'what is this a kind of'),
    "find": ('which record holds this binding', 'find the record with a role filler', 'locate a bound pair', 'search absorbed records', 'find bind role filler'),
    "game_world": ('massive sharded game world', 'open world of game shards', 'lazy grid game world', 'streaming game world', 'huge multiplayer world'),
    "hypervector": ('encode as a first-class hypervector', 'raw vector plus metadata', 'hypervector object', 'typed hypervector', 'encode to a hypervector wrapper'),
    "is_a": ('is this a kind of that', 'taxonomic membership', 'does concept belong to category', 'check is-a relationship', 'subtype check'),
    "is_deterministic": ('is this function deterministic', 'does it return the same result every time', 'check determinism', 'bit-identical repeatability', 'is the output reproducible'),
    "light": ('add a light to a scene', 'directional or point light', 'sun light source', 'scene lighting object', 'place a light'),
    "make_cloud": ('render a volumetric cloud', 'make a cloud image', 'volumetric cloud in one call', 'draw a cloud', 'cloud render'),
    "serve": ('serve this query preemptively', 'answer from memory or a tool first',
              'try the substrate before the model', 'preemptive answer without an llm',
              'serve results from a learned tool'),
    "table_as_of": ('query a table at an earlier version', 'what did this table look like at version 3',
                    'select from a past snapshot of the table', 'time travel query over a table',
                    'read the table as it was before the change'),
    "role": ('run a focused agent role on the bus', 'subscribe a handler to a topic', 'lab agent that reacts to findings',
             'chain agents by topic', 'focused swarm member'),
    "roles": ('list the roles on the bus', 'which agent roles are registered', 'how many messages each role handled'),
    "escalations": ('questions escalated to a human', 'what the swarm could not answer', 'the escalation ledger'),
    "resolve": ('record the human answer to an escalation', 'human resolves an escalated question', 'teach the resolution and propagate it'),
    "codebase_sync": ('teach the swarm the codebase', 'sync knowledge of the code after edits', 'shared codebase understanding'),
    "api_learn": ('learn an api from its spec', 'hook up a non llm model', 'connect a timesfm style forecaster',
                  'teach lecore a new web service', 'register an external service', 'learn an openapi spec'),
    "api_toolbox": ('list learned apis', 'which external services do I know', 'learned api roster',
                    'what apis can I call', 'show my learned services'),
    # sweep 124: the catalog exam's twelve invisible faculties (rank 61 of 60 for their natural
    # asks) -- each shadowed by a DESCRIPTIVE card for the same capability sitting at top-1 (the
    # sweep-92 wave). Bare-name aliases from the user's mouth; NEVER descriptive renames.
    "brep_boolean": ('cut a hole in a mesh with another mesh', 'boolean subtract two meshes',
                     'union or intersect two solids', 'csg on meshes'),
    "mesh_qem_decimate": ('reduce the polygon count', 'simplify a mesh to fewer faces',
                          'decimate a mesh', 'lower poly version of a mesh'),
    "points_to_mesh": ('turn a point cloud into a surface', 'reconstruct a mesh from points',
                       'surface from a scan', 'point cloud to mesh'),
    "map_bind": ('store a key value pair in a vector', 'bind a key to a value',
                 'put a record into a hypervector', 'vector dictionary write'),
    "unbind_keys": ('pull a value back out of a bundled vector', 'read a key out of a superposition',
                    'unbind a role from a bundle', 'vector dictionary read'),
    "learn_cleanup": ('clean up a noisy hypervector', 'snap a noisy vector to its nearest atom',
                      'denoise a hypervector against the codebook', 'cleanup memory for vectors'),
    "find_capability": ('what can this engine do', 'find the faculty for my task', 'search capabilities',
                        'which function does this', 'discover a capability by description'),
    "file_replace": ('edit a source file', 'replace text in a file', 'patch a file in place',
                     'surgical edit of source code'),
    "rigid_body": ('bounce rigid bodies off each other', 'simulate colliding solid objects',
                   'rigid body physics', 'boxes falling and bouncing'),
    "denoise_tensor": ('make my picture less grainy', 'remove noise from an image array',
                       'denoise a tensor', 'clean up a grainy photo'),
    "advect_field": ('make smoke swirl', 'advect a field with a velocity', 'move a density through a flow',
                     'swirling fluid transport'),
    "lookup": ('look up a word in the dictionary', 'define this word', 'word definition and synonyms',
               'english dictionary lookup', 'what does this word mean'),
    "study": ('comprehend a directory in one call', 'walk and digest a tree', 'study this folder',
              'one call code and doc comprehension', 'macro study of a repository'),
    "make_observer": ('custom sensor from sensitivity curves', 'build an observer', 'spectral sensor with channels', 'define a camera response', 'per-channel sensor'),
    "make_scene": ('build a scene from nested objects', 'assemble a scene from a list', 'scene from objects', 'construct a nested scene', 'scene builder from parts'),
    "make_table": ('ingest tabular data', 'load a table of records', 'rows into a vsa table', 'tabular data to vectors', 'make a table from dicts'),
    "material": ('a pbr material', 'physically based material', 'material with textures', 'role-filler material record', 'surface material'),
    "measure": ('variance harness', 'mean spread and confidence interval', 'measure with error bars', 'bootstrap a number honestly', 'report a metric with variance'),
    "plan": ('bake a route to the next decision', 'short executable plan', 'corridor to the next waypoint', 'plan a path to a goal', 'route to decision point'),
    "query": ('run a sql query', 'select from where', 'query records with sql', 'small sql over a table', 'sql subset query'),
    "read": ('pre-learn word co-occurrence', 'learn word meanings from text', 'read a corpus', 'warm up text meaning', 'learn from reading'),
    "recall": ('nearest stored item', 'recall the closest memory', 'find the nearest stored individual', 'exact nearest neighbour recall', 'retrieve closest stored vector'),
    "refine": ('improve a result with a critic', 'iterate against a scorer', 'refine with feedback', 'critic-guided improvement', 'produce then critique then redo'),
    "route": ('decide which skill to use', 'agent decision node', 'should i act or choose', 'route a task to a skill', 'pick the winning skill'),
    "sample_from": ('draw a symbol from a distribution', 'weighted random pick', 'sample with temperature', 'nucleus sampling', 'sample from a weighted dict'),
    "sampler": ('placeable read probe', 'read a field at a point', 'read-dual of a field effect', 'probe a field value', 'sample a field with a probe'),
    "scatter": ('scatter points onto a grid', 'deposit values with a kernel', 'splat onto a grid', 'scatter is the bundle', 'rasterize points to a field'),
    "scene": ('compose visual attribute scenes', 'scene coder', 'encode and decode a scene', 'compose decompose a scene', 'visual scene algebra'),
    "scene_to_render": ('flatten a scene for the path tracer', 'scene to sdf and material', 'prepare a scene for rendering', 'brain-to-muscle scene handoff', 'bake a scene to renderable'),
    "sdf_render": ('march an sdf to a mesh', 'sdf tree to triangles', 'turn an sdf into a mesh', 'marching cubes on an sdf', 'sdf to drawable mesh'),
    # C1: PBR Neutral tonemap (a postfx stage) -- make the tonemapper discoverable via the chain faculties.
    "post_process": ('apply a post processing chain', 'tonemap a rendered frame', 'pbr neutral tonemap',
                     'khronos neutral tone mapping', 'tonemap that holds hue better than aces', 'colour grade a frame',
                     'aces or pbr neutral tonemapping', 'gltf standard tonemapper', 'run a postfx chain on a frame'),
    "postfx_chain": ('build a post processing chain', 'exposure bloom tonemap vignette chain', 'pbr neutral or aces stage',
                     'assemble a colour grade pipeline', 'tonemapping and grading program'),
    # ITEM 9: PostChain.to_glsl / mind.postfx_to_glsl compiles the pointwise colour pipeline to a fragment shader.
    "postfx_to_glsl": ('emit glsl for a post processing chain', 'fragment shader for a color grading pipeline',
                       'postfx to webgl', 'run the colour grade on the gpu', 'compile a postfx chain to a shader',
                       'post processing chain to glsl', 'gpu color pipeline shader', 'live video grading shader',
                       'export a colour pipeline as glsl', 'tone map and grade in a fragment shader'),
    # C5: closed-form patterns emit to WGSL (WebGPU) too, not just GLSL.
    "pattern_to_wgsl": ('emit a pattern as wgsl', 'webgpu shader for a pattern', 'checker or dots as wgsl',
                        'procedural background for webgpu', 'wgsl fragment for a pattern', 'pattern field as wgsl'),
    # C4: bloom as a multi-pass GPU DAG (single-pass postfx_to_glsl must refuse it -- no intermediate texture).
    "bloom_passes": ('multi pass bloom shader', 'emit bloom as several gpu passes', 'render target ping pong bloom',
                     'separable blur passes for glow', 'bloom pass dag with wiring', 'gpu bloom the honest way'),
    # C2: pattern_to_glsl now emits the GPU-reproducible noise32/fbm32 (int64 noise/fbm still refuse -- see module note).
    "pattern_to_glsl": ('emit a pattern as glsl', 'gpu reproducible noise', 'value noise that runs on the gpu',
                        'fractal noise shader that matches cpu', 'emit noise to glsl', 'noise32 or fbm32 shader',
                        'pattern field as a fragment shader', 'checker or stripes or noise as glsl'),
    # ITEM 6: inpaint/harmonic_fill now accept (H,W,C) -- an RGB image fills in one call. The image-oriented phrasings
    # ("inpaint an rgb image", "fill a masked area of a photo") did not rank on the field-oriented docstring alone.
    "inpaint": ('fill the gaps in a field', 'impute missing values', 'inpaint an rgb image', 'fill missing regions in a color image',
                'fill a masked area of a photo', 'inpaint all channels at once', 'fill holes in an image', 'fill in erased pixels',
                'harmonic fill a field', 'label propagation into holes'),
    "harmonic_fill": ('laplace fill a continuous field', 'harmonic inpaint an image', 'fill holes in an rgb image',
                      'smooth interpolation into holes', 'minimal energy fill', 'inpaint a colour image per channel'),
    # ITEM 5: segment_image gained max_dim (bound the pixel-scaled sweep, upsample masks back to full size). These
    # latency-oriented phrasings did not rank on the docstring alone -- aliased from the interactive caller's mouth.
    "segment_image": ('segment a photo into regions', 'demux an image by colour', 'segment a large image quickly',
                      'bound the segmentation resolution', 'downsample before segmenting', 'fast segmentation of a big photo',
                      'limit segmentation to a max dimension', 'segment at a capped resolution', 'object regions from a photo'),
    # ITEM 8: the emitted shader gained a camera="uniforms" mode (orbit camera driven by host-bound uAngle/uHeight/
    # uDist), so a WebGL2 host can spin/zoom without string-splicing the source. These abstract phrasings ("spin and
    # zoom", "controllable camera") did not rank on the faculty docstring alone -- aliased from the host's mouth.
    "to_shadertoy": ('export an sdf to shadertoy glsl', 'get the shadertoy code for a shape', 'sdf to glsl shader',
                     'shadertoy shader with orbit camera', 'glsl with a controllable camera', 'movable camera shader',
                     'spin and zoom the shadertoy scene', 'camera uniforms in the emitted glsl',
                     'orbit camera uniforms uAngle uHeight uDist'),
    "sdf_shader": ('emit a glsl fragment shader for an sdf', 'sdf to shadertoy shader', 'raymarch shader from an sdf',
                   'glsl shader with orbit camera uniforms', 'controllable camera in the emitted glsl',
                   'movable camera raymarcher', 'spin and zoom the emitted shader'),
    "selection": ('select objects in a scene', 'selection set', 'query objects into a selection', 'scene selection helper', 'pick a set of objects'),
    "simulation": ('wrap a solver in a step loop', 'generic simulation scaffold', 'step any time-stepped solver', 'simulation loop wrapper', 'run any solver step by step'),
    "step_at": ('the i-th step of a plan', 'get a plan step by index', 'which step is next', 'read a stored plan step', 'plan step at index'),
    "surface_mesh": ('re-extract a mesh from a field', 'field to drawable mesh', 'sculpt re-extract step', 'turn any field into a mesh', 'remesh from a field'),
    "to_state": ('snapshot the mind for saving', 'serialize the learned mind', 'save state with quantization', "export the mind's state", 'dump the brain to state'),
    "trace": ('provenance of a result', 'style and material trace', 'where did this come from', 'full provenance answer', 'explain the origin'),
}


def _selftest():
    """A DATA module still gets a real selftest (sweep 129): the alias table is the discoverability
    contract for every bare-name faculty, and the failures that hurt are silent ones. Assert the
    exact shape the catalog reads (str -> tuple of str), that NO alias is INERT (an alias with zero
    content words can never be matched -- the sweep-109 catch), and that every key names a REAL
    UnifiedMind method -- a typo here is a dark faculty nobody would notice until a stranger
    could not find it."""
    # the catalog's OWN tokenizer decides what a content word is -- a stricter rule here
    # flagged 'new box' as inert when find_capability matches it fine (caught first run)
    from holographic.caching_and_storage.holographic_catalog import _tokens
    assert isinstance(_METHOD_ALIASES, dict) and _METHOD_ALIASES, "empty alias table"
    for k, v in _METHOD_ALIASES.items():
        assert isinstance(k, str) and isinstance(v, tuple) and v, "bad row for %r" % k
        for a in v:
            assert isinstance(a, str) and _tokens(a), \
                "INERT alias (no content words) under %r: %r" % (k, a)
    from holographic.misc.holographic_unified import UnifiedMind
    dark = [k for k in _METHOD_ALIASES if not callable(getattr(UnifiedMind, k, None))]
    assert not dark, "alias keys that name no UnifiedMind method: %s" % dark[:8]
    print("holographic_catalog_aliases selftest OK -- %d verbs, %d aliases, none inert, all real"
          % (len(_METHOD_ALIASES), sum(len(v) for v in _METHOD_ALIASES.values())))


if __name__ == "__main__":
    _selftest()
